### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by mictadlo** [dmitrymyl/TADselect#3]
Hi,
I ran [SALSA](https://github.com/machinegun/SALSA) which is a tool to scaffold long read assemblies with Hi-C data. 

SALSA did not create for each chromosome FASTA files?

How could I use SALSA's output and use your pipeline in order to create for each chromosome FASTA files?

Thank you in advance,

Michal

**Comment by dmitrymyl** [comment]
Hi,
The TADselect module is used to call topologically associated domains (TADs) from Hi-C contact maps and other relevant biological data. This task has nothing in common with contig assembly from Hi-C data. TADselect cannot be used with SALSA's output.
